## MSCA 37010  Programming for Analytics
### Week 8 Assignment (100 Points)

#### Question 1. Create an 4x4 array of the random samples from a uniform distribution over [0, 1) (5 points)

In [1]:
import numpy as np
import pandas as pd
import csv

In [2]:
np.random.rand(4,4)

array([[0.14189124, 0.40663005, 0.48058881, 0.34475628],
       [0.18831274, 0.32941004, 0.20087697, 0.53719598],
       [0.67703148, 0.35975165, 0.26497182, 0.72200233],
       [0.03099697, 0.47899706, 0.68883731, 0.21245791]])

#### Question 2. Create an 4x4 array of the random samples from a "standard normal" distribution (5 points)

In [3]:
import numpy as np 
np.random.randn(4,4)

array([[ 1.40693453, -0.27020051,  1.8574105 , -0.67736129],
       [ 1.05181555,  0.66082207,  0.84362323, -1.4350621 ],
       [-0.61756058, -0.0833076 , -1.46706522, -0.5402191 ],
       [-1.74774702,  0.92617703, -1.73436749, -0.37819377]])

#### Question 3. Use the two arrays from Questions 1 and 2 to perform addition, subtraction, multiplication, and division. (10 point)

In [4]:
np.random.rand(4,4) + np.random.randn(4,4)

array([[ 1.16269774,  0.92695024, -0.33836378, -1.14177543],
       [-0.0114034 ,  0.6482618 ,  1.25193776,  0.10783386],
       [ 1.03828552,  0.46246486,  0.57151154,  0.03205603],
       [ 0.3610794 ,  0.92144959,  0.50522313,  0.59317528]])

In [5]:
np.random.rand(4,4) - np.random.randn(4,4)

array([[ 0.45796415,  1.08451244, -0.33183623, -0.82856268],
       [ 1.67933607, -0.10112435,  0.54121326,  0.27184594],
       [ 1.12981164,  2.17874871, -1.25002885, -0.32841743],
       [-0.23701557, -2.46171127, -0.00528277,  1.39199311]])

In [6]:
np.random.rand(4,4) * np.random.randn(4,4)

array([[ 0.88797128,  1.03343351, -0.09594686,  0.11743836],
       [ 0.11369999, -0.04927829, -0.13792051, -0.1907598 ],
       [ 0.06926504, -0.31930881, -0.04708753, -0.24214878],
       [ 0.16735689, -0.17611627,  0.75204422, -0.86507895]])

In [7]:
np.random.rand(4,4) / np.random.randn(4,4)

array([[-0.75485565, -0.31993212, -0.16110039,  1.0632589 ],
       [ 0.27952737, -1.97501579,  0.91163051, -3.65450982],
       [ 2.03154884,  0.33314268, -0.9087536 ,  3.95577532],
       [41.48939456,  0.32283115, -0.55983558,  7.84632925]])

#### Question 4. Use the 3x3 array to do the following: (Hint: Refer to Lecture Notes) (10 Point)

arr33 = np.array(([5,10,15],[15,25,40],[35,30,25]))

1) Index array([15, 25, 40]) (2.5 points)

2) Index the element of 30 (2.5 points)

3) Index (2,2) array from top right corner (2.5 points)

4) Index the bottom row (2.5 points)

In [8]:
arr33 = np.array(([5,10,15],[15,25,40],[35,30,25]))
arr33[1]

array([15, 25, 40])

In [9]:
arr33[2, 1]

30

In [10]:
arr33[0:2, 1:3]

array([[10, 15],
       [25, 40]])

In [11]:
arr33[2,]

array([35, 30, 25])

#### Question 5. Use np.random.randint(0,50,25) (5 Points)

1) Reshape this one dimensional array to a 5x5 array; (2.5 points)

2) Use the output from 1) to make an one dimentional array.  (2.5 points)

In [12]:
arr = np.random.randint(0,50,25)
arr2 = arr.reshape(5,5)
arr2

array([[30,  1, 45, 40,  8],
       [27, 41,  6, 18, 24],
       [ 3,  7,  6, 25, 26],
       [42,  4, 48, 47, 34],
       [ 9, 11, 24, 42, 35]])

In [13]:
arr2.flatten()

array([30,  1, 45, 40,  8, 27, 41,  6, 18, 24,  3,  7,  6, 25, 26, 42,  4,
       48, 47, 34,  9, 11, 24, 42, 35])

#### Question 6. Use the array a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]) and b = np.array([[10, 11, 12]]) (5 Points)

1) Stack two arrays vertically

2) Stack two arrays horizontally

In [14]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[10, 11, 12]])
np.vstack((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [15]:
np.hstack((a,b.T))

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 11],
       [ 7,  8,  9, 12]])

#### Question 7. Use Numpy to import WCFrequency data (10 Points)

1) View the top few records (2.5 points)

2) View the bottom 5 records (2.5 points)

2) View the entire file (5 points)

In [16]:
import os
os.chdir(r'C:\Users\chris\PythonProgramming\Data')
with open('WCFrequency.csv', 'r') as f:
    data = list(csv.reader(f, delimiter = ','))
data[:5]

[['class', 'year', 'payroll', 'claimcount'],
 ['1', '1', '32.321999', '1'],
 ['1', '2', '33.778999', '4'],
 ['1', '3', '43.548', '3'],
 ['1', '4', '46.686001', '5']]

In [17]:
# OR,
np.genfromtxt('WCFrequency.csv', delimiter=',', dtype="<U16", autostrip=True)[:5]

array([['class', 'year', 'payroll', 'claimcount'],
       ['1', '1', '32.321999', '1'],
       ['1', '2', '33.778999', '4'],
       ['1', '3', '43.548', '3'],
       ['1', '4', '46.686001', '5']], dtype='<U16')

In [18]:
data[-5:]

[['133', '3', '69.913002', '0'],
 ['133', '4', '46.289001', '0'],
 ['133', '5', '91.119003', '0'],
 ['133', '6', '78.456001', '1'],
 ['133', '7', '84.362', '2']]

In [20]:
# OR,
np.genfromtxt('WCFrequency.csv', delimiter=',', dtype="<U16", autostrip=True)[-10:]

array([['132', '5', '35.412998', '2'],
       ['132', '6', '16.983999', '1'],
       ['132', '7', '18.797001', '0'],
       ['133', '1', '66.212997', '2'],
       ['133', '2', '65.695999', '0'],
       ['133', '3', '69.913002', '0'],
       ['133', '4', '46.289001', '0'],
       ['133', '5', '91.119003', '0'],
       ['133', '6', '78.456001', '1'],
       ['133', '7', '84.362', '2']], dtype='<U16')

In [21]:
!cat WCfrequency.csv

class,year,payroll,claimcount
1,1,32.321999,1
1,2,33.778999,4
1,3,43.548,3
1,4,46.686001,5
1,5,34.713001,1
1,6,32.856998,3
1,7,36.599998,4
2,1,45.994999,3
2,2,37.888,1
2,3,34.581001,0
2,4,28.298,0
2,5,45.264999,2
2,6,39.945,0
2,7,39.321999,4
3,1,289.047,5
3,2,392.17599,8
3,3,368.98199,8
3,4,323.76999,8
3,5,385.22198,16
3,6,346.39001,8
3,7,324.13199,9
4,1,0,0
4,2,0,0
4,3,0,0
4,4,0.037,0
4,5,0,0
4,6,0,0
4,7,0,0
5,1,310.38901,15
5,2,292.46399,10
5,3,262.56,18
5,4,273.25699,25
5,5,372.73001,27
5,6,263.44299,20
5,7,355.82599,28
6,1,291.784,27
6,2,267.439,44
6,3,288.55499,40
6,4,308.36401,31
6,5,387.095,40
6,6,351.44501,34
6,7,342.51801,37
7,1,0,0
7,2,0,0
7,3,0,0
7,4,0,0
7,5,0,0
7,6,0,0
7,7,0,0
8,1,41.403,3
8,2,34.066002,11
8,3,32.729,4
8,4,32.235001,0
8,5,32.777,2
8,6,28.620001,4
8,7,24.263,1
9,1,6.4520001,0
9,2,6.927,1
9,3,5.8509998,0
9,4,3.033,1
9,5,1.7869999,0
9,6,1.074,1
9,7,0.685,0
10,1,537.31097,11
10,2,569.04102,12
10,3,597.146,15
10,4,570.29498,15
10,5,1116.75,18
10,6,774.45398,10
1

In [22]:
# OR,
np.genfromtxt('WCFrequency.csv', delimiter=',', dtype="<U16", autostrip=True)

array([['class', 'year', 'payroll', 'claimcount'],
       ['1', '1', '32.321999', '1'],
       ['1', '2', '33.778999', '4'],
       ...,
       ['133', '5', '91.119003', '0'],
       ['133', '6', '78.456001', '1'],
       ['133', '7', '84.362', '2']], dtype='<U16')

#### Question 8. Use the following array to find all values less than 0.5 and greater than 0.1 (5 points)

twentyfive_vals = np.random.random((25,))


In [23]:
twentyfive_vals = np.random.random((25,))
twentyfive_vals[(twentyfive_vals > 0.1) & (twentyfive_vals < 0.5)]

array([0.18076505, 0.35140364, 0.10661792, 0.11769916, 0.39918984,
       0.34780533, 0.22749675, 0.16453479, 0.37639533, 0.21122133,
       0.32960082, 0.24386698, 0.3998674 ])

#### Question 9. Numpy Indexing and Selection: Now you will be given a matrix mat and be asked to replicate the resulting matrix outputs (15 points)

In [24]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [25]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [26]:
mat[3,4]


20

In [27]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [28]:
mat[4,:]

array([21, 22, 23, 24, 25])

In [29]:
mat[-1,:]

array([21, 22, 23, 24, 25])

In [30]:
mat[3:5,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### Question 10. Create a 3x3 matrix with values ranging from 0 to 8 (5 points)¶

In [31]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

####  Question 11: Create a new completely independent object B copied from A (so-called "deep copy") (5 points)

A = np.array([[1, 2], [3, 4]])

In [32]:
# Type your answers here
A = np.array([[1, 2], [3, 4]])
B = np.copy(A)
B

array([[1, 2],
       [3, 4]])

#### Question 12. Create a series using [40,42,43,44,39] with index ['Monday', 'Tuesday','Wednesday', 'Thursday','Friday'] (5 points)

In [33]:
import pandas as pd
d=pd.Series([40,42,43,44,39], ['Monday', 'Tuesday','Wednesday', 'Thursday','Friday'])
d

Monday       40
Tuesday      42
Wednesday    43
Thursday     44
Friday       39
dtype: int64

#### Question 13. How to get the positions where elements of two arrays match? (5 points)

In [34]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [35]:
np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)

#### Question 14. How to extract the desired numbers below between a given range from a numpy array? (5 points)

In [36]:
a = np.array([2, 6, 1, 9, 10, 3, 27])

In [37]:
a[np.where((a>=6)&(a<=10))]

array([ 6,  9, 10])

#### Question 15. Find the mean, median, standard deviation of iris's sepallength (1st column) (5 points)

In [38]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

In [39]:
np.mean(sepallength)

5.843333333333334

In [40]:
np.median(sepallength)

5.8

In [41]:
np.std(sepallength)

0.8253012917851409